name: ${name}
version: ${project.version}
main: ${mainClass}
author: royalkingkb
description: Economy plugin for Steve Cinema
depend: [Vault]
api-version: 1.16
commands:
  balance:
    description: Check your balance
    aliases: [bal]
  showbalance:
    description: Show your balance to the server
    aliases: [showbal]
  pay:
    description: Give silver to someone else
    aliases: [givesilver]
  ecoadmin:
    description: Admin economy commands
    permission: stevecinema.economy.admin
